//! NIST P-256 (secp256r1, prime256v1), taught from limbs to validated points.
//!
//! # What P-256 is
//!
//! P-256 is the short Weierstrass curve `y^2 = x^3 - 3x + b` over the prime field
//! `GF(p)`, `p = 2^256 - 2^224 + 2^192 + 2^96 - 1`, with a prime group order `n` and cofactor
//! one. Its domain parameters are published in NIST SP 800-186 §3.2.1.3. TLS 1.3 names the
//! curve `secp256r1` for key exchange and `ecdsa_secp256r1_sha256` for signatures; SSH names it
//! `ecdh-sha2-nistp256` and `ecdsa-sha2-nistp256`.
//!
//! This module supplies the group. It does not define a key exchange, a signature scheme, or a
//! wire format beyond the uncompressed SEC 1 point encoding that both consumers share.
//!
//! # Standards notation in Rust
//!
//! | Publication name | Rust representation | Meaning |
//! | --- | --- | --- |
//! | `p` | [`field::MODULUS`] | The field prime, four little-endian `u64` limbs. |
//! | `a = -3`, `b` | folded into the addition formula; [`field::CURVE_B`] | Curve coefficients. |
//! | `n` | [`scalar::ORDER`] | Prime order of the group generated by `G`. |
//! | `G = (G_x, G_y)` | [`point::GENERATOR_X`], [`point::GENERATOR_Y`] | The fixed base point. |
//! | `h = 1` | documented, not stored | Every on-curve point except `O` has order `n`. |
//! | field element | private [`field::FieldElement`] | A residue modulo `p`. |
//! | scalar | private [`scalar::Scalar`] | A residue modulo `n`. |
//! | `(X : Y : Z)` | private [`point::ProjectivePoint`] | Homogeneous projective coordinates. |
//! | `(x, y)` | private [`point::AffinePoint`] | Validated affine coordinates. |
//! | `O` | `ProjectivePoint::identity()` = `(0 : 1 : 0)` | The point at infinity. |
//! | `04 || x || y` | `AffinePoint::to_bytes` | SEC 1 §2.3.3 uncompressed encoding. |
//!
//! # Arithmetic walkthrough
//!
//! 1. [`arithmetic`] implements 256-bit unsigned integers as `[u64; 4]`, schoolbook
//!    multiplication into `[u64; 8]`, and reduction by a modulus `m` with `2^256 - m < 2^224`.
//!    Both `p` and `n` satisfy that bound, so one readable reduction serves both.
//! 2. [`field`] and [`scalar`] wrap that arithmetic in distinct types so a coordinate can never
//!    be added to a signature scalar by accident.
//! 3. [`point`] implements Renes–Costello–Batina complete projective addition (Algorithm 4 for
//!    `a = -3`), which is correct for every input pair including `P + P`, `P + (-P)`, and
//!    `P + O`. Doubling reuses the same formula. Scalar multiplication always executes 256
//!    additions, 256 doublings, and masked selections.
//! 4. Affine decoding rejects a wrong prefix, a coordinate `>= p`, and any `(x, y)` that does
//!    not satisfy the curve equation, and encoding always produces the canonical uncompressed
//!    form.
//!
//! # Common mistakes and non-goals
//!
//! - Do not use an incomplete addition law with a fixed-structure ladder; the exceptional cases
//!   `P = Q` and `P = -Q` silently produce wrong points. The complete formula has no such cases.
//! - Do not skip the curve-equation check on received points. An invalid-curve point lets a
//!   peer learn private-key bits from the ECDH result.
//! - Compressed encodings, point-decompression square roots, P-384, P-521, hash-to-curve, and
//!   any optimized field arithmetic are deliberately outside this readable profile.
//!
//! # Readable source map
//!
//! - [`arithmetic`] owns limb representation, comparison, and modular reduction.
//! - [`field`] owns residues modulo `p`, inversion, and canonical byte encoding.
//! - [`scalar`] owns residues modulo `n`, canonical range checks, and inversion.
//! - [`point`] owns the complete addition law, fixed-structure scalar multiplication, the
//!   generator, and validated affine encoding.
//!
//! # Evidence and security status
//!
//! The private layers have focused tests for reduction identities, inversion, the generator's
//! curve membership, `[n]G = O`, and the RFC 5903 §8.1 public keys. Public evidence lives with
//! the ECDH and ECDSA consumers. No side-channel or audit claim is made.

// This teaching page intentionally links into the private executable-specification layers.
#![allow(rustdoc::private_intra_doc_links)]

pub(crate) mod arithmetic;
pub(crate) mod field;
pub(crate) mod point;
pub(crate) mod scalar;

/// Current project lifecycle classification for the P-256 group arithmetic.
pub const SECURITY_STATUS: crate::security::SecurityStatus =
    crate::security::SecurityStatus::Recommended;
