//! AES-128 key-expansion constants and word operations.
//!
//! ## Standards ownership
//!
//! [NIST FIPS 197 §5.2][fips-197] defines `KEYEXPANSION()`. Table 5 publishes the ten round
//! constants that AES-128 consumes. Equation 5.10 defines `ROTWORD()` as a one-byte cyclic left
//! permutation, and equation 5.11 defines `SUBWORD()` as four independent `SBOX()` applications.
//! Appendix A.1 publishes intermediate values after each operation for a complete AES-128 key.
//!
//! This module composes those constants and individual word operations into Algorithm 2's
//! AES-128-specific 44-word recurrence. The resulting private schedule yields one distinct
//! four-word round-key copy at a time for `ADDROUNDKEY()`.
//!
//! A word passed to these helpers is a transient secret-bearing value. It is moved into and out of
//! each operation rather than retained beyond expansion. [`KeySchedule`] is non-`Clone` and
//! zeroizes its complete word array on drop. Each [`RoundKey`] copy is independently zeroizing.
//!
//! [fips-197]: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197-upd1.pdf

use super::{field::add, key::RoundKey, state::BLOCK_LEN, substitution::substitute_byte};
use zeroize::Zeroize;

/// Number of bytes in one AES key-schedule word.
const WORD_BYTES: usize = 4;

/// One transient key-schedule word in the byte order printed by FIPS 197.
type Word = [u8; WORD_BYTES];

/// Number of input-key words in AES-128, called `Nk` by FIPS 197.
const KEY_WORDS: usize = 4;

/// Number of cipher rounds in AES-128, called `Nr` by FIPS 197.
const ROUND_COUNT: usize = 10;

/// Number of round keys, including the key addition before round one.
const ROUND_KEY_COUNT: usize = ROUND_COUNT + 1;

/// Number of words generated by AES-128 `KEYEXPANSION()`.
///
/// FIPS 197 §5.2 specifies `4 * (Nr + 1)` words: four words for each of eleven key additions.
const EXPANDED_WORDS: usize = WORD_BYTES * ROUND_KEY_COUNT;

/// The ten AES round constants from FIPS 197 §5.2, Table 5.
///
/// Array index zero represents the standard's one-based `Rcon[1]`. Only the leftmost byte is
/// nonzero; Table 5 defines it as `x^(j-1)` in `GF(2^8)` for `1 <= j <= 10`. Literal published
/// values keep this transcription reviewable independently from the field arithmetic layer.
const ROUND_CONSTANTS: [Word; 10] = [
    [0x01, 0x00, 0x00, 0x00],
    [0x02, 0x00, 0x00, 0x00],
    [0x04, 0x00, 0x00, 0x00],
    [0x08, 0x00, 0x00, 0x00],
    [0x10, 0x00, 0x00, 0x00],
    [0x20, 0x00, 0x00, 0x00],
    [0x40, 0x00, 0x00, 0x00],
    [0x80, 0x00, 0x00, 0x00],
    [0x1b, 0x00, 0x00, 0x00],
    [0x36, 0x00, 0x00, 0x00],
];

/// Cyclically move a word's first byte to its final position.
///
/// **Standard mapping:** FIPS 197 equation 5.10 defines
/// `ROTWORD([a0,a1,a2,a3]) = [a1,a2,a3,a0]`. The fixed array's `rotate_left(1)` operation is that
/// byte permutation exactly; it does not reinterpret the word as an endian-dependent integer.
#[must_use]
fn rotate_word(mut word: Word) -> Word {
    word.rotate_left(1);
    word
}

/// Apply the calculated forward AES S-box to every byte of a word.
///
/// **Standard mapping:** FIPS 197 equation 5.11 defines
/// `SUBWORD([a0,...,a3]) = [SBOX(a0),...,SBOX(a3)]`. The loop preserves all four byte positions
/// and calls the exhaustively Table-4-tested substitution layer independently at each one.
#[must_use]
fn substitute_word(mut word: Word) -> Word {
    for byte in &mut word {
        *byte = substitute_byte(*byte);
    }

    word
}

/// Add two key-schedule words byte by byte.
///
/// **Standard mapping:** Algorithm 2 uses word-level XOR both for the transformed every-fourth
/// word and for ordinary recurrence steps. FIPS 197 §4.1 extends XOR across corresponding bits;
/// this helper calls the byte field-addition operation at all four unchanged positions.
///
/// Both input copies are transient secret material and are zeroized before the result is returned.
#[must_use]
fn add_words(mut left: Word, mut right: Word) -> Word {
    let result = core::array::from_fn(|byte_index| add(left[byte_index], right[byte_index]));

    left.zeroize();
    right.zeroize();
    result
}

/// The complete secret AES-128 key schedule: 44 words in Algorithm 2 order.
///
/// The type deliberately implements neither `Clone`, `Copy`, nor `Debug`. Callers request one
/// [`RoundKey`] at a time, making every additional secret copy visible and independently
/// zeroizing.
pub(super) struct KeySchedule {
    words: [Word; EXPANDED_WORDS],
}

impl KeySchedule {
    /// Expand one 128-bit AES key into 44 words.
    ///
    /// **Standard mapping:** FIPS 197 §5.2 Algorithm 2 copies the four input words first. For
    /// every later `w[i]`, `temp` begins as `w[i-1]`. When `i` is a multiple of AES-128's
    /// `Nk = 4`, it becomes `SUBWORD(ROTWORD(temp)) XOR Rcon[i/Nk]`; the new word is then
    /// `w[i-4] XOR temp`. AES-128 does not use Algorithm 2's AES-256-only branch.
    ///
    /// Explicit four-byte arrays avoid host-endian integer conversion. Transient copies are
    /// zeroized after their result is installed into the owning schedule.
    #[must_use]
    pub(super) fn expand(key: &[u8; BLOCK_LEN]) -> Self {
        let mut words = [[0_u8; WORD_BYTES]; EXPANDED_WORDS];

        for (word_index, word) in words[..KEY_WORDS].iter_mut().enumerate() {
            let first_key_byte = word_index * WORD_BYTES;
            word.copy_from_slice(&key[first_key_byte..first_key_byte + WORD_BYTES]);
        }

        for word_index in KEY_WORDS..EXPANDED_WORDS {
            let mut temporary = words[word_index - 1];

            if word_index % KEY_WORDS == 0 {
                temporary = substitute_word(rotate_word(temporary));
                let round_constant = ROUND_CONSTANTS[word_index / KEY_WORDS - 1];
                temporary = add_words(temporary, round_constant);
            }

            let earlier_word = words[word_index - KEY_WORDS];
            let mut expanded_word = add_words(earlier_word, temporary);
            words[word_index].copy_from_slice(&expanded_word);
            expanded_word.zeroize();
        }

        Self { words }
    }

    /// Copy one of the eleven four-word round keys into a distinct zeroizing value.
    ///
    /// `round` follows FIPS 197 Algorithm 1: zero selects the pre-round key and ten selects the
    /// final-round key. Internal cipher composition calls this only for `0..=10`; fixed array
    /// indexing retains a panic if that invariant is violated during development.
    #[must_use]
    pub(super) fn round_key(&self, round: usize) -> RoundKey {
        let first_word = round * KEY_WORDS;
        let words = core::array::from_fn(|offset| self.words[first_word + offset]);

        RoundKey::from_words(words)
    }
}

impl Drop for KeySchedule {
    fn drop(&mut self) {
        self.words.zeroize();
    }
}

#[cfg(test)]
mod unit {
    use super::{KeySchedule, ROUND_CONSTANTS, add_words, rotate_word, substitute_word};

    /// FIPS 197-upd1 Appendix A.1's complete AES-128 word schedule, in `w[i]` order.
    const APPENDIX_A1_WORDS: [[u8; 4]; 44] = [
        [0x2b, 0x7e, 0x15, 0x16],
        [0x28, 0xae, 0xd2, 0xa6],
        [0xab, 0xf7, 0x15, 0x88],
        [0x09, 0xcf, 0x4f, 0x3c],
        [0xa0, 0xfa, 0xfe, 0x17],
        [0x88, 0x54, 0x2c, 0xb1],
        [0x23, 0xa3, 0x39, 0x39],
        [0x2a, 0x6c, 0x76, 0x05],
        [0xf2, 0xc2, 0x95, 0xf2],
        [0x7a, 0x96, 0xb9, 0x43],
        [0x59, 0x35, 0x80, 0x7a],
        [0x73, 0x59, 0xf6, 0x7f],
        [0x3d, 0x80, 0x47, 0x7d],
        [0x47, 0x16, 0xfe, 0x3e],
        [0x1e, 0x23, 0x7e, 0x44],
        [0x6d, 0x7a, 0x88, 0x3b],
        [0xef, 0x44, 0xa5, 0x41],
        [0xa8, 0x52, 0x5b, 0x7f],
        [0xb6, 0x71, 0x25, 0x3b],
        [0xdb, 0x0b, 0xad, 0x00],
        [0xd4, 0xd1, 0xc6, 0xf8],
        [0x7c, 0x83, 0x9d, 0x87],
        [0xca, 0xf2, 0xb8, 0xbc],
        [0x11, 0xf9, 0x15, 0xbc],
        [0x6d, 0x88, 0xa3, 0x7a],
        [0x11, 0x0b, 0x3e, 0xfd],
        [0xdb, 0xf9, 0x86, 0x41],
        [0xca, 0x00, 0x93, 0xfd],
        [0x4e, 0x54, 0xf7, 0x0e],
        [0x5f, 0x5f, 0xc9, 0xf3],
        [0x84, 0xa6, 0x4f, 0xb2],
        [0x4e, 0xa6, 0xdc, 0x4f],
        [0xea, 0xd2, 0x73, 0x21],
        [0xb5, 0x8d, 0xba, 0xd2],
        [0x31, 0x2b, 0xf5, 0x60],
        [0x7f, 0x8d, 0x29, 0x2f],
        [0xac, 0x77, 0x66, 0xf3],
        [0x19, 0xfa, 0xdc, 0x21],
        [0x28, 0xd1, 0x29, 0x41],
        [0x57, 0x5c, 0x00, 0x6e],
        [0xd0, 0x14, 0xf9, 0xa8],
        [0xc9, 0xee, 0x25, 0x89],
        [0xe1, 0x3f, 0x0c, 0xc8],
        [0xb6, 0x63, 0x0c, 0xa6],
    ];

    /// Published constant evidence from FIPS 197-upd1 §5.2, Table 5.
    #[test]
    fn all_ten_round_constants_match_table_five_in_order() {
        assert_eq!(
            ROUND_CONSTANTS,
            [
                [0x01, 0x00, 0x00, 0x00],
                [0x02, 0x00, 0x00, 0x00],
                [0x04, 0x00, 0x00, 0x00],
                [0x08, 0x00, 0x00, 0x00],
                [0x10, 0x00, 0x00, 0x00],
                [0x20, 0x00, 0x00, 0x00],
                [0x40, 0x00, 0x00, 0x00],
                [0x80, 0x00, 0x00, 0x00],
                [0x1b, 0x00, 0x00, 0x00],
                [0x36, 0x00, 0x00, 0x00],
            ]
        );
    }

    /// Published intermediate evidence from FIPS 197-upd1 Appendix A.1, `i = 4`.
    #[test]
    fn first_rotword_matches_the_published_appendix_a1_intermediate() {
        assert_eq!(
            rotate_word([0x09, 0xcf, 0x4f, 0x3c]),
            [0xcf, 0x4f, 0x3c, 0x09]
        );
    }

    /// Published intermediate evidence from FIPS 197-upd1 Appendix A.1, `i = 4`.
    #[test]
    fn first_subword_matches_the_published_appendix_a1_intermediate() {
        let rotated = rotate_word([0x09, 0xcf, 0x4f, 0x3c]);

        assert_eq!(substitute_word(rotated), [0x8a, 0x84, 0xeb, 0x01]);
    }

    /// Published intermediate evidence from FIPS 197-upd1 Appendix A.1, `i = 8`.
    ///
    /// This second sample makes a coincidental first-word-only implementation observable.
    #[test]
    fn second_rotword_and_subword_match_appendix_a1() {
        let rotated = rotate_word([0x2a, 0x6c, 0x76, 0x05]);

        assert_eq!(rotated, [0x6c, 0x76, 0x05, 0x2a]);
        assert_eq!(substitute_word(rotated), [0x50, 0x38, 0x6b, 0xe5]);
    }

    /// Published intermediate evidence from FIPS 197-upd1 Appendix A.1, `i = 4`.
    #[test]
    fn word_additions_match_both_published_first_recurrence_xors() {
        let after_round_constant = add_words([0x8a, 0x84, 0xeb, 0x01], [0x01, 0x00, 0x00, 0x00]);

        assert_eq!(after_round_constant, [0x8b, 0x84, 0xeb, 0x01]);
        assert_eq!(
            add_words(after_round_constant, [0x2b, 0x7e, 0x15, 0x16]),
            [0xa0, 0xfa, 0xfe, 0x17]
        );
    }

    /// Exhaustive published word evidence from FIPS 197-upd1 Appendix A.1.
    #[test]
    fn complete_key_expansion_matches_all_44_appendix_a1_words() {
        let key = [
            0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf,
            0x4f, 0x3c,
        ];
        let schedule = KeySchedule::expand(&key);

        assert_eq!(schedule.words, APPENDIX_A1_WORDS);
    }

    /// Published grouping evidence from FIPS 197-upd1 Appendix A.1 and §5.1.4.
    #[test]
    fn round_keys_select_each_consecutive_group_of_four_words() {
        let key = [
            0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf,
            0x4f, 0x3c,
        ];
        let schedule = KeySchedule::expand(&key);

        for round in 0..=10 {
            let round_key = schedule.round_key(round);

            for word_offset in 0..4 {
                let expected_word = APPENDIX_A1_WORDS[round * 4 + word_offset];

                for (byte_index, expected_byte) in expected_word.into_iter().enumerate() {
                    assert_eq!(
                        round_key.byte(word_offset, byte_index),
                        expected_byte,
                        "round {round}, word {word_offset}, byte {byte_index}"
                    );
                }
            }
        }
    }
}
