"""Fast policy tests: hand-authored dependency/ownership oracles, no builds or network."""

import copy
from pathlib import Path
import subprocess
import tempfile
import unittest

from gate import check_plan, check_release, check_results
from plan import BNB, MACROS, SOCKS, NOSTD, Package, affected_packages, changed_paths, select
from prepare import event_options, is_release_merge, is_release_pr


def fixture():
    # Deliberately small, independently specified topology. These edges express
    # consumer contracts, not a snapshot generated by the selector under test.
    return {
        MACROS: Package("bitsandbytes-macros", set()),
        BNB: Package("bitsandbytes", {MACROS}),
        SOCKS: Package("socks", {BNB}),
        "compression": Package("rsl-compression", set()),
        "crypto": Package("rsl-crypto", set()),
        "crypto-legacy": Package("rsl-crypto-legacy", {"crypto"}),
        "pki/asn1": Package("rsl-asn1", {BNB}),
        "pki/x509": Package("rsl-x509", {"pki/asn1"}),
        "pki/validation": Package("rsl-pki", {"pki/x509", "crypto"}),
        "rsl": Package("rsl", {"compression", "pki/validation"}),
        "bitsandbytes/fuzz": Package("bnb-fuzz", {BNB}, False, ("decode", "stream_decode")),
        "crypto/fuzz": Package("crypto-fuzz", {"crypto"}, False, ("aead_open",)),
        "pki/fuzz": Package("pki-fuzz", {"pki/asn1", "pki/x509", "pki/validation", "crypto"},
                            False, ("certificate_parse",)),
        f"{SOCKS}/fuzz": Package("socks-fuzz", {SOCKS}, False, ("session",)),
        NOSTD: Package("nostd-check", {BNB}, False),
        "tools/rust-skills/crates/xtask": Package("xtask", set(), False),
    }


def planned(paths=(), **kwargs):
    graph = fixture()
    plan = select(paths, graph, graph, **kwargs)
    plan.update(base="a" * 40, head="b" * 40, release_candidate=False)
    return plan


def results(plan):
    return {"plan": {"result": "success"}, "policy": {"result": "success"},
            "checks": {"result": "success" if plan["profiles"] else "skipped"},
            "fuzz": {"result": "success" if plan["fuzz"] else "skipped"}}


class SelectionTests(unittest.TestCase):
    def test_prose_does_not_select_rust_or_fuzz(self):
        plan = planned(["bitsandbytes/bnb/DESIGN.md", "README.md", "bitsandbytes/docs/RELEASING.md"])
        self.assertEqual(plan["profiles"], [])
        self.assertEqual(plan["fuzz"], [])
        self.assertFalse(plan["full"])

    def test_socks_does_not_retest_upstream_bnb_or_unrelated_crypto(self):
        plan = planned([f"{SOCKS}/src/blocking.rs"])
        self.assertEqual(plan["packages"], ["socks"])
        self.assertEqual(set(plan["profiles"]), {"workspace", "msrv", "socks", "deny"})
        self.assertEqual([(f["root"], f["target"]) for f in plan["fuzz"]],
                         [(f"{SOCKS}/fuzz", "session")])

    def test_compression_covers_facade_but_not_facades_other_dependencies(self):
        plan = planned(["compression/src/lib.rs"])
        self.assertEqual(plan["packages"], ["rsl", "rsl-compression"])
        self.assertIn("facades", plan["profiles"])
        self.assertEqual(plan["fuzz"], [])

    def test_crypto_covers_legacy_and_pki_consumers(self):
        plan = planned(["crypto/src/lib.rs"])
        self.assertEqual(set(plan["packages"]), {"rsl", "rsl-crypto", "rsl-crypto-legacy", "rsl-pki"})
        self.assertEqual({f["root"] for f in plan["fuzz"]}, {"crypto/fuzz", "pki/fuzz"})

    def test_bnb_covers_protocol_pki_and_fuzz_consumers_not_crypto(self):
        plan = planned([f"{BNB}/src/lib.rs"])
        self.assertTrue({"socks", "rsl-asn1", "rsl-x509", "rsl-pki"} <= set(plan["packages"]))
        self.assertNotIn("rsl-crypto", plan["packages"])
        self.assertEqual({f["root"] for f in plan["fuzz"]},
                         {"bitsandbytes/fuzz", "pki/fuzz", f"{SOCKS}/fuzz"})

    def test_macros_propagate_through_runtime(self):
        self.assertIn("socks", planned([f"{MACROS}/src/lib.rs"])["packages"])

    def test_shared_vectors_are_test_inputs_not_docs(self):
        for suffix in ("hex", "md"):
            with self.subTest(suffix=suffix):
                plan = planned([f"pki/tests/vectors/nist-pkits/example.{suffix}"])
                self.assertTrue({"rsl-asn1", "rsl-x509", "rsl-pki"} <= set(plan["packages"]))
                self.assertIn("pki/fuzz", {f["root"] for f in plan["fuzz"]})

    def test_generated_skill_markdown_selects_its_validation(self):
        plan = planned(["tools/rust-skills/generated/agent-skills/rust-core/SKILL.md"])
        self.assertIn("rust-skills", plan["profiles"])
        self.assertNotIn("workspace", plan["profiles"])

    def test_fixture_readme_is_not_a_prose_exemption(self):
        self.assertIn("bnb", planned([f"{BNB}/tests/fixtures/README.md"])["profiles"])

    def test_rustdoc_only_source_edits_are_still_code(self):
        self.assertIn("bnb", planned([f"{BNB}/src/lib.rs"])["profiles"])

    def test_detached_lockfile_selects_only_its_workspace(self):
        plan = planned(["crypto/fuzz/Cargo.lock"])
        self.assertEqual(plan["packages"], [])
        self.assertEqual({f["root"] for f in plan["fuzz"]}, {"crypto/fuzz"})

    def test_shared_or_unknown_changes_force_full_coverage(self):
        for path in ("Cargo.lock", "Cargo.toml", ".cargo/config.toml", "AGENTS.md",
                     "scripts/ci/plan.py", ".github/workflows/ci.yml", "new-tool/input.dat"):
            with self.subTest(path=path):
                plan = planned([path])
                self.assertTrue(plan["full"])
                self.assertIn("rsl-crypto", plan["packages"])
                self.assertIn("socks", plan["packages"])
                self.assertIn("package", plan["profiles"])

    def test_domain_ci_change_does_not_expand_to_unrelated_crypto(self):
        plan = planned([".github/ci/bnb.toml"])
        self.assertIn("bnb", plan["profiles"])
        self.assertNotIn("rsl-crypto", plan["packages"])

    def test_removed_dependency_still_selects_its_old_consumer(self):
        old = fixture()
        new = copy.deepcopy(old)
        new[SOCKS].dependencies.clear()
        plan = select([f"{BNB}/src/lib.rs"], old, new)
        self.assertIn("socks", plan["packages"])

    def test_deleted_package_selects_remaining_old_consumers(self):
        old = fixture()
        new = copy.deepcopy(old)
        del new["compression"]
        new["rsl"].dependencies.remove("compression")
        plan = select(["compression/src/lib.rs"], old, new)
        self.assertIn("rsl", plan["packages"])
        self.assertTrue(plan["full"])

    def test_unregistered_manifest_cannot_hide_behind_full_coverage(self):
        for path in ("new-tool/Cargo.toml", f"{BNB}/unknown/Cargo.toml"):
            with self.subTest(path=path), self.assertRaises(ValueError):
                planned([path])

    def test_removed_detached_workspace_with_no_consumers_forces_full_coverage(self):
        old = fixture()
        new = copy.deepcopy(old)
        del new["crypto/fuzz"]
        plan = select(["crypto/fuzz/Cargo.toml"], old, new)
        self.assertTrue(plan["full"])
        self.assertIn("rsl-crypto", plan["packages"])

    def test_rename_checks_old_and_new_owners(self):
        graph = fixture()
        plan = select(["compression/src/old.rs", "crypto/src/new.rs"], graph, graph)
        self.assertTrue({"rsl-compression", "rsl-crypto", "rsl-pki"} <= set(plan["packages"]))

    def test_development_dependency_cycles_terminate(self):
        graph = {"a": Package("a", {"b"}), "b": Package("b", {"a"})}
        self.assertEqual(set(affected_packages({"a": {"changed"}}, graph, graph)), {"a", "b"})

    def test_selection_is_deterministic_and_monotone(self):
        a, b = f"{SOCKS}/src/lib.rs", "crypto/src/lib.rs"
        self.assertEqual(planned([a, b]), planned([b, a, b]))
        self.assertTrue(set(planned([a])["roots"]) <= set(planned([a, b])["roots"]))

    def test_release_prose_still_requires_complete_release_profiles(self):
        plan = planned(["README.md"], release=True)
        self.assertTrue({"bnb", "socks", "no-std", "public-api", "semver", "package"}
                        <= set(plan["profiles"]))
        self.assertNotIn("rsl-crypto", plan["packages"])
        self.assertFalse(plan["full"])


class GateTests(unittest.TestCase):
    def test_omitted_coverage_cannot_pass_against_the_recomputed_plan(self):
        expected = planned([f"{BNB}/src/lib.rs"])
        check_plan(expected, copy.deepcopy(expected))
        for key in ("roots", "packages", "profiles", "fuzz", "paths"):
            with self.subTest(key=key):
                actual = copy.deepcopy(expected)
                actual[key] = actual[key][1:]
                with self.assertRaises(ValueError):
                    check_plan(actual, expected)

    def test_empty_successful_docs_plan_legitimately_skips_heavy_jobs(self):
        plan = planned(["README.md"])
        check_results(plan, results(plan))

    def test_selected_job_cannot_skip_fail_or_cancel(self):
        plan = planned([f"{SOCKS}/src/lib.rs"])
        for job in ("plan", "policy", "checks", "fuzz"):
            for result in ("skipped", "failure", "cancelled"):
                with self.subTest(job=job, result=result):
                    needs = results(plan)
                    needs[job]["result"] = result
                    with self.assertRaises(ValueError):
                        check_results(plan, needs)

    def test_missing_dependency_is_not_success(self):
        plan = planned()
        needs = results(plan)
        del needs["plan"]
        with self.assertRaises(ValueError):
            check_results(plan, needs)

    def test_changed_fuzz_budget_is_not_accepted(self):
        plan = planned(["crypto/src/lib.rs"])
        plan["fuzz"] = copy.deepcopy(plan["fuzz"])
        plan["fuzz"][0]["args"] = ["-runs=1"]
        with self.assertRaises(ValueError):
            check_results(plan, results(plan))

    def test_scoped_plan_cannot_omit_base(self):
        plan = planned()
        plan["base"] = None
        with self.assertRaises(ValueError):
            check_results(plan, results(plan))

    def test_release_receipt_requires_exact_run_and_complete_coverage(self):
        plan = planned(release=True)
        plan["release_candidate"] = True
        report = {"head": plan["head"], "run_id": 42, "run_attempt": 2,
                  "event": "push", "plan": plan, "needs": results(plan)}
        arguments = dict(sha=plan["head"], run_id=42, attempt=2, graph=fixture())
        check_release(report, **arguments)
        for field, wrong in (("head", "c" * 40), ("run_id", 43), ("run_attempt", 1)):
            with self.subTest(field=field):
                bad = copy.deepcopy(report)
                bad[field] = wrong
                with self.assertRaises(ValueError):
                    check_release(bad, **arguments)
        for field in ("profiles", "packages", "roots", "fuzz"):
            with self.subTest(field=field):
                bad = copy.deepcopy(report)
                bad["plan"][field] = []
                with self.assertRaises(ValueError):
                    check_release(bad, **arguments)

    def test_ordinary_docs_receipt_cannot_qualify_publication(self):
        plan = planned(["README.md"])
        report = {"head": plan["head"], "run_id": 42, "run_attempt": 1,
                  "event": "push", "plan": plan, "needs": results(plan)}
        with self.assertRaises(ValueError):
            check_release(report, sha=plan["head"], run_id=42, attempt=1, graph=fixture())

    def test_manually_forced_release_checks_do_not_authorize_publication(self):
        plan = planned(release=True)
        report = {"head": plan["head"], "run_id": 42, "run_attempt": 1,
                  "event": "workflow_dispatch", "plan": plan, "needs": results(plan)}
        with self.assertRaisesRegex(ValueError, "merged release candidate"):
            check_release(report, sha=plan["head"], run_id=42, attempt=1, graph=fixture())


class GitBoundaryTests(unittest.TestCase):
    def test_deleted_renamed_and_unusual_paths_survive_git_transport(self):
        with tempfile.TemporaryDirectory(prefix="rsl-ci-git-test-") as directory:
            root = Path(directory)
            def git(*args):
                return subprocess.run(["git", *args], cwd=root, check=True,
                                      stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout
            # No commits/hooks/identity are needed: immutable trees are enough for git diff.
            git("init", "--quiet")
            (root / "old name.rs").write_text("same contents\n")
            git("add", "old name.rs")
            old = git("write-tree").decode().strip()
            (root / "old name.rs").rename(root / "new\nname.rs")
            git("add", "--all")
            new = git("write-tree").decode().strip()
            self.assertEqual(changed_paths(root, old, new), ["new\nname.rs", "old name.rs"])


class EventTests(unittest.TestCase):
    def test_manual_run_without_base_and_schedule_require_full_coverage(self):
        options = dict(base="", full=False, release=False, repository="RawSocketLabs/rsl", prefix="release-plz-")
        self.assertEqual(event_options(Path.cwd(), {}, "workflow_dispatch", **options), ("", True, False, False))
        options["base"] = "a" * 40
        self.assertEqual(event_options(Path.cwd(), {}, "schedule", **options), ("a" * 40, True, False, False))

    def test_local_explicit_base_selects_affected_checks(self):
        self.assertEqual(event_options(Path.cwd(), {}, "workflow_dispatch", base="abc", full=False,
                                       release=False, repository="RawSocketLabs/rsl", prefix="release-plz-"),
                         ("abc", False, False, False))

    def test_manual_release_input_only_requests_extra_checks(self):
        self.assertEqual(event_options(Path.cwd(), {}, "workflow_dispatch", base="abc", full=False,
                                       release=True, repository="RawSocketLabs/rsl", prefix="release-plz-"),
                         ("abc", False, True, False))

    def test_associated_pr_must_be_the_exact_release_merge(self):
        repository, sha = "RawSocketLabs/rsl", "a" * 40
        pr = {"merged_at": "2026-09-12", "merge_commit_sha": sha,
              "head": {"ref": "release-plz-2026", "repo": {"full_name": repository}},
              "base": {"ref": "main", "repo": {"full_name": repository}}}
        self.assertTrue(is_release_merge(pr, repository, sha, "release-plz-"))
        self.assertFalse(is_release_merge(pr, repository, "b" * 40, "release-plz-"))
        self.assertFalse(is_release_merge({**pr, "merged_at": None}, repository, sha, "release-plz-"))

    def test_unknown_event_is_not_a_docs_run(self):
        with self.assertRaises(ValueError):
            event_options(Path.cwd(), {}, "pull_request_target", base="", full=False, release=False,
                          repository="RawSocketLabs/rsl", prefix="release-plz-")

    def test_release_association_requires_the_configured_repository_and_prefix(self):
        repository = "RawSocketLabs/rsl"
        pr = {"head": {"ref": "release-plz-2026-09-12", "repo": {"full_name": repository}},
              "base": {"ref": "main", "repo": {"full_name": repository}}}
        self.assertTrue(is_release_pr(pr, repository, "release-plz-"))
        for replacement in ({"ref": "ci/affected-validation", "repo": {"full_name": repository}},
                            {"ref": "release-plz-untrusted", "repo": {"full_name": "fork/rsl"}},
                            {"ref": "release-plz-deleted", "repo": None}):
            with self.subTest(head=replacement):
                self.assertFalse(is_release_pr({**pr, "head": replacement}, repository, "release-plz-"))


if __name__ == "__main__":
    unittest.main()
