/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  // Ignore automated commits generated by migration tools (e.g. the Blacksmith
  // runner-migration wizard) whose messages don't follow Conventional Commits.
  ignores: [(message) => /^Migrate .+ to .+/i.test(message)],
};
