/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  // Ignore automated commits generated by the Blacksmith runner-migration
  // wizard whose messages don't follow Conventional Commits.
  ignores: [(message) => /^Migrate .+ to Blacksmith\b/i.test(message)],
};
