#!/usr/bin/env python3
"""Generate rsl-deps/blessed-versions.toml from rsl-deps' manifest — the single source of truth
for blessed external versions. Crates that can't route through the facade (derive macros:
serde, thiserror, utoipa, …) stay DIRECT deps in consumers; the drift check (tools/check-drift.py)
compares a consumer's direct deps against this file and flags any on a different major line.
A CI job regenerates this and fails if it drifts from the committed copy."""
import tomllib, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
deps = tomllib.loads((ROOT / "rsl-deps" / "Cargo.toml").read_text()).get("dependencies", {})

blessed = {}
for name, spec in sorted(deps.items()):
    req = spec if isinstance(spec, str) else (spec.get("version") if isinstance(spec, dict) else None)
    if req and req[0].isdigit():
        blessed[name] = req

out = ["# GENERATED by tools/gen-blessed.py — do not edit. `rsl-deps` is the source of truth for",
       "# blessed external versions. A consumer keeping any of these as a DIRECT dependency (the",
       "# derive crates that can't route through the facade) should stay on the same major line;",
       "# tools/check-drift.py enforces it in the consumer's CI.", "", "[versions]"]
out += [f'{n} = "{r}"' for n, r in blessed.items()]
(ROOT / "rsl-deps" / "blessed-versions.toml").write_text("\n".join(out) + "\n")
print(f"blessed-versions.toml: {len(blessed)} crates")
